import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { Button, ToggleButton } from "remote/components";

// If the following import (and related components below) are removed - then the app works.
import { ButtonFederated, ToggleButtonFederated } from "remote2/components";

export async function getServerSideProps() {
  return { props: { data: 'Hello from the server!' } }
}

export default function Home({ data }: { data: string }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <h1>Module fedetation demo</h1>
        <p>{data}</p>
        <Button label="Button from remote" />
        <ToggleButton label="Toggle Button from remote" content="Content from remote" />
        <ButtonFederated label="Button from remote2" />
        <ToggleButtonFederated label="Toggle Button from remote2" content="Content from remote2" />
      </main>
    </>
  );
}
